spring:
  application:
    name: cloudadmin
  security:
    user:
      name: admin
      password: admin

server:
  port: 10086

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@eureka:9000/eureka
      #,http://eureka:eureka@duplicate:9001/eureka
    register-with-eureka: true
  instance:
    #显示ip
    prefer-ip-address: true
    #心跳检查时间间隔 默认30s
    lease-renewal-interval-in-seconds: 2
    #超过时间认为服务已死 默认90s
    lease-expiration-duration-in-seconds: 5
    metadata-map:
      user: ${spring.security.user.name}
      password: ${spring.security.user.password}