server:
  port: 7090

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  redis:
    host: '{cipher}AQBGtWWt0/cyG03MNGM6Fbkwm4xN48viAq0i/oA5kz5P4Z/rSs9RMbDqbt14brnlM6oQhaDXJX6UM2fcKXbd7KBrGTniOeOgOkfch9wY8Pp5Xgwdq8rsGbXac3Fr8RvZIZLhu+F0qOhPcXvskuFRBVLFzTgI1XeVpFMrr0Jgequa+wIt9sQzsb4GJwo3/4Hx4mAarBL1eNgKqUDnGqmY0kqzBe9bOD0AySkjIv3QHW1Qh+d39IuAN0ySHxJREjcfzohCoTUSr+3A6uu9RLQIL0Ie9afmPk1GolPpm+iZJqSKNupvzo6oP6KEjwu7MJ8WlOr7nRF85WFLfpid79enwq2tdeGzSWtHIHSF2kuZYTLMpEAEHHtFYOlWVC44SxJnkoBhUDTO/IiV4J3gJDgJnVx3'
    port: '{cipher}AQA0F1tlDZaxceOEIFOuou9zeHz8dDpZlUFW/VzRos3B11r7Xtnkh4uFcJz4bExmWqaQ18NaA0Ia02bTh5aENKmqyE0VaofG7vS8x1JDHlS88pRiRMXNBCuc+NITbTkTTF75gOIF2wwUL/OcBrrLtgutVeiGTvfy13YcIurSGUFYHuQ2GFOywyQi3w/O5vpw7KqvlGzKpZBWEk1X2/V1p2pFnQKdybSg7aclwb24J0G7K03BpUHbv/dYg1fPaPUBW4oQ6VbNnL0FocL+TrTLc0F07jX94tWnCkYBTNb7Zsragoit/HnLLREYgQSjn64TUs+cCXv/lAMJZknis/bha03HO+K2AeSWAYu/2ziI3bvF2N3nIx44dz2pM0Ic5TOX6ps='
    database: 0
    timeout: 3000ms
    password: '{cipher}AQAEJIScqQgXHqd12OZ8tZZFDwVR2SMdA+CzPT2MTnZaj1Nxc3RDnSmZi1EwIQvVOO4JHnNDqwYYobdJ7aKGwPJ972rUUh0pWpDiEhE3cL6kUgaF76yMOKcJnPX+GUc/Qy3AUMZT0npzz/6SxYQWYCgiaWJJKH89ElE+Hrep+57W/nXvC2wKxfJAaC8VNCTN9jdbo9tLc/Dh3QVtLbgg4RCdcyS0SpEu04yqOlm27MJCDk2H3+JdoSohsKBV8XFX8ScA2dlnlyQIk0jyihc3WlrZpDP3SOH2Xc5FaFToxwQUz/bq5rEgLjrXBtuB6IHpZxA+cu1iLcvHf1q+4VmC+xATSe3R2W27Efk9/vFgZAzxecPUQ1IFwv78wfHWh8gyAsQ='
  security:
    user:
      name: demo
      password: demo
  profiles:
    active: eureka
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: '{cipher}AQAWXicDb6gT+r8RcUriJVt5K22s3ywjY6UjP68hQ6XACrQyWBRX5EqjKhjukyWwfsFgKluxwBQFWF3/mmgNWh9ruUzGRe8hx7A8rWUhEi9bzFNOQp/ekVXh+hfnthsf1RSlIDr6DHYPEBhEpnpIU08IUTmwo7CB4cRbENSW1zat+t+FjQIsRaAvqERXMCXF+YeTCJvnFp1LZ3RmxcZDXKiWG6FHxn3gRgbF60REamLZgtcxrdlkUv0bFrTKhE/kca6xSFcIUJ5dVrQ9TkVaeB65bc54WXgWM+TCCcFM5Qjcq+M07RT8RaqhU2OsRdGkplJ4SLPshW1cNo5h85P1vIO+kRMcsJgKzYx+FqLIRGHg4YMiJZEUX7ySp7p4GP45pC8hfn3qnYtUyzBK+Vsxty3udq1hVNVl5jqI1AgNMvVeVe4EWEHMZKAVCh9gQKVT48Hhwi+547YUjj6ELeCdkKbiOE1SSUvrI1en76b9NqeRlw7GmeN2TDEDYLI6ZdvCLng='
      username: root
      password: immortal
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 10
      min-idle: 10
      max-active: 100
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #      filters: stat,wall
      #      use-global-data-source-stat: true
      #      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      #      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

management:
  #默认健康检查全部禁用
#  health:
#    defaults:
#      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'