server:
  port: 8010

spring:
  security:
    user:
      name: material
      password: material
  profiles:
    active: eureka
  application:
    name: material
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: '{cipher}AQAWXicDb6gT+r8RcUriJVt5K22s3ywjY6UjP68hQ6XACrQyWBRX5EqjKhjukyWwfsFgKluxwBQFWF3/mmgNWh9ruUzGRe8hx7A8rWUhEi9bzFNOQp/ekVXh+hfnthsf1RSlIDr6DHYPEBhEpnpIU08IUTmwo7CB4cRbENSW1zat+t+FjQIsRaAvqERXMCXF+YeTCJvnFp1LZ3RmxcZDXKiWG6FHxn3gRgbF60REamLZgtcxrdlkUv0bFrTKhE/kca6xSFcIUJ5dVrQ9TkVaeB65bc54WXgWM+TCCcFM5Qjcq+M07RT8RaqhU2OsRdGkplJ4SLPshW1cNo5h85P1vIO+kRMcsJgKzYx+FqLIRGHg4YMiJZEUX7ySp7p4GP45pC8hfn3qnYtUyzBK+Vsxty3udq1hVNVl5jqI1AgNMvVeVe4EWEHMZKAVCh9gQKVT48Hhwi+547YUjj6ELeCdkKbiOE1SSUvrI1en76b9NqeRlw7GmeN2TDEDYLI6ZdvCLng='
      username: root
      password: immortal
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 10
      min-idle: 10
      max-active: 100
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #      filters: stat,wall
      #      use-global-data-source-stat: true
      #      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      #      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

management:
  #默认健康检查全部禁用
#  health:
#    defaults:
#      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          enabled: true
          semaphore:
            maxConcurrentRequests: 10
          thread:
            timeoutInMilliseconds: 1000

